apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: exo1-dep
  name: exo1-dep
  namespace: mathieu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exo1-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: exo1-dep
    spec:
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: gp2-claim-1 
      initContainers:
      - image: busybox
        name: init-busy
        command:
          - sh
          - -c
          - 'echo $firstname; echo $firstname >> /data/myfile; date >> /data/myfile; cat /data/myfile'
        envFrom:
          - configMapRef:
              name: exo2-configmap
        volumeMounts:
          - name: mypvc
            mountPath: /data
      containers:
      - image: nginx:latest
        name: nginx
        resources: 
          requests:
            cpu: 20m
            memory: 12Mi
          limits:
            cpu: 30m
            memory: 16Mi
        ports:
          - containerPort: 80
        volumeMounts:
          - name: mypvc
            mountPath: /data
        envFrom:
          - configMapRef:
              name: exo2-configmap

status: {}
